version: "3.8"

services:
  db:
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    container_name: "development-mysql"
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql

  migration:
    image: flyway/flyway
    depends_on:
      - db
    container_name: development-flyway
    volumes:
      - ./database/migration/schema:/flyway/sql

volumes:
  data-volume:
